require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe SlackIntegrationsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # SlackIntegration. As you add validations to SlackIntegration, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET #index" do
    it "assigns all slack_integrations as @slack_integrations" do
      slack_integration = SlackIntegration.create! valid_attributes
      get :index, params: {}
      expect(assigns(:slack_integrations)).to eq([slack_integration])
    end
  end

  describe "GET #show" do
    it "assigns the requested slack_integration as @slack_integration" do
      slack_integration = SlackIntegration.create! valid_attributes
      get :show, params: {:id => slack_integration.to_param}
      expect(assigns(:slack_integration)).to eq(slack_integration)
    end
  end

  describe "GET #new" do
    it "assigns a new slack_integration as @slack_integration" do
      get :new, params: {}
      expect(assigns(:slack_integration)).to be_a_new(SlackIntegration)
    end
  end

  describe "GET #edit" do
    it "assigns the requested slack_integration as @slack_integration" do
      slack_integration = SlackIntegration.create! valid_attributes
      get :edit, params: {:id => slack_integration.to_param}
      expect(assigns(:slack_integration)).to eq(slack_integration)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new SlackIntegration" do
        expect {
          post :create, params: {:slack_integration => valid_attributes}
        }.to change(SlackIntegration, :count).by(1)
      end

      it "assigns a newly created slack_integration as @slack_integration" do
        post :create, params: {:slack_integration => valid_attributes}
        expect(assigns(:slack_integration)).to be_a(SlackIntegration)
        expect(assigns(:slack_integration)).to be_persisted
      end

      it "redirects to the created slack_integration" do
        post :create, params: {:slack_integration => valid_attributes}
        expect(response).to redirect_to(SlackIntegration.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved slack_integration as @slack_integration" do
        post :create, params: {:slack_integration => invalid_attributes}
        expect(assigns(:slack_integration)).to be_a_new(SlackIntegration)
      end

      it "re-renders the 'new' template" do
        post :create, params: {:slack_integration => invalid_attributes}
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested slack_integration" do
        slack_integration = SlackIntegration.create! valid_attributes
        put :update, params: {:id => slack_integration.to_param, :slack_integration => new_attributes}
        slack_integration.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested slack_integration as @slack_integration" do
        slack_integration = SlackIntegration.create! valid_attributes
        put :update, params: {:id => slack_integration.to_param, :slack_integration => valid_attributes}
        expect(assigns(:slack_integration)).to eq(slack_integration)
      end

      it "redirects to the slack_integration" do
        slack_integration = SlackIntegration.create! valid_attributes
        put :update, params: {:id => slack_integration.to_param, :slack_integration => valid_attributes}
        expect(response).to redirect_to(slack_integration)
      end
    end

    context "with invalid params" do
      it "assigns the slack_integration as @slack_integration" do
        slack_integration = SlackIntegration.create! valid_attributes
        put :update, params: {:id => slack_integration.to_param, :slack_integration => invalid_attributes}
        expect(assigns(:slack_integration)).to eq(slack_integration)
      end

      it "re-renders the 'edit' template" do
        slack_integration = SlackIntegration.create! valid_attributes
        put :update, params: {:id => slack_integration.to_param, :slack_integration => invalid_attributes}
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested slack_integration" do
      slack_integration = SlackIntegration.create! valid_attributes
      expect {
        delete :destroy, params: {:id => slack_integration.to_param}
      }.to change(SlackIntegration, :count).by(-1)
    end

    it "redirects to the slack_integrations list" do
      slack_integration = SlackIntegration.create! valid_attributes
      delete :destroy, params: {:id => slack_integration.to_param}
      expect(response).to redirect_to(slack_integrations_url)
    end
  end

end
